name: CI build

on:
  push:
    branches: [ '**' ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS-11
            name: macOS x86_64
            arch: x86_64
            toolchain: default.cmake

          - os: windows-latest
            name: Windows x86_64
            arch: x86_64

          - os: ubuntu-20.04
            container: ubuntu:18.04
            name: Linux x86_64
            install: curl pkg-config zip build-essential libsystemd-dev zlib1g-dev libssl-dev
            arch: x86_64

          - os: ubuntu-20.04
            container: ubuntu:18.04
            name: Linux arm
            install: curl pkg-config zip crossbuild-essential-armhf libsystemd-dev zlib1g-dev libssl-dev
            toolchain: Linux-arm.cmake
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
            arch: arm

          - os: ubuntu-20.04
            container: ubuntu:18.04
            name: Linux arm64
            install: curl pkg-config zip crossbuild-essential-arm64 libsystemd-dev zlib1g-dev libssl-dev
            toolchain: Linux-arm64.cmake
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
            arch: arm64

    steps:
      - name: install tools
        if: ${{ matrix.install != null }}
        run: |
          apt -y update
          apt -y install ${{ matrix.install }}

      - name: install contemporary git
        if: ${{ matrix.container != null }}
        run: |
          apt -y update
          apt -y install software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt -y update
          apt -y install git
          git --version

      - name: install contemporary cmake
        if: ${{ matrix.container != null }}
        run: |
          curl -L https://cmake.org/files/v3.24/cmake-3.24.2-linux-x86_64.sh -o cmake.sh
          bash cmake.sh --skip-license --prefix=/usr/local
          rm cmake.sh

      - name: checkout workspace
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: make build dir
        run: cmake -E make_directory ./build

      - name: configure cmake
        env:
          TOOLCHAIN: ${{ matrix.toolchain && format('./toolchains/{0}', matrix.toolchain) || '' }}
        run: cmake ${{matrix.cmake_opts}} -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN}" -S . -B ./build

      - name: build ziti-edge-tunnel bundle target
        run: cmake --build ./build --target bundle --verbose

      - name: list bundle artifacts
        run: ls -R
        working-directory: ./build/bundle/

      - name: list program artifacts
        run: ls -R
        working-directory: ./build/programs/ziti-edge-tunnel/

      - name: upload bundle artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}
          path: |
            ./build/bundle/ziti-edge-tunnel-*.zip
          if-no-files-found: error
