name: Alert Mattermost ~dev-notifications

on:
  issues:
  issue_comment:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
  pull_request:
    types: [opened, reopened]
  push:
  fork:
  release:
    types: [released]

jobs:
  ziti-webhook:
    runs-on: ubuntu-latest
    name: Alert Mattermost - All Events Except PR Events That are Not Approvals
    env:
      ZHOOK_URL: ${{ secrets.ZHOOK_URL }}
    steps:
    - uses: openziti/ziti-mattermost-action-py@main
      if: env.ZHOOK_URL && github.event_name != 'pull_request_review'
      with:
        zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhookUrl: ${{ secrets.ZHOOK_URL }}
        eventJson: ${{ toJson(github.event) }}
        senderUsername: "GitHubZ"
        destChannel: "dev-notifications"
    - uses: openziti/ziti-mattermost-action-py@main
      if: env.ZHOOK_URL && github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
      with:
        zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhookUrl: ${{ secrets.ZHOOK_URL }}
        eventJson: ${{ toJson(github.event) }}
        senderUsername: "GitHubZ"
        destChannel: "dev-notifications"
